name: 'Merge developement to master Action'
description: 'Action to merge the development branch to master.'
runs:
  using: "composite"
  steps:
    - name: Merge development to master
      shell: bash
      run: |
        #switch to the development branch
        git checkout development
        # switch to master and merge development
        git checkout main
        git merge development
        # push merged changes to remote
        git push origin main