name: Merge development branch to master
on: [workflow_dispatch]
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        path: source
    
    - name: Update master
      uses: ./script/action-git-development-to-master
      with:
        path: source
          