name: Github actions Release
on: [workflow_dispatch]
jobs:
  Github Actions Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: ./gradlew library:publish --no-parallel --no-daemon
        env:
          mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
          mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}