name: Test Input in action
on: 
    workflow_dispatch:
      inputs:
        userInput:
          description: 'Enter some value'     
          required: true
    
jobs:
    User-Input:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                distribution: 'zulu'
                java-version: '17'
            - run: kotlin .github/scripts/input-demo.main.kts ${{github.event.inputs.userInput}} qwe

